In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Slicing

In [6]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [7]:
arr[6:9]

array([7, 8, 9])

## Compute statistical measures (sum, mean, maximum, and minimum)

In [8]:
arr.sum()

np.int64(55)

In [9]:
arr.max()

np.int64(10)

In [10]:
arr.min()

np.int64(1)

## Broadcasting to modify the array elements

In [17]:
arr + 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [18]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [20]:
arr / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [21]:
arr * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])